services
  backend:
    image: docker push 94822karthik/cricket-score-backend:latest
    container_name: backend
    ports:
      - "8000:8000"
    environment: 
      MLFLOW_TRACKING_URI: "http://mlflow:5000"

  frontend:
    image: docker push 94822karthik/cricket-score-frontend:latest
    container_name: frontend
    depends_on:
       - backend
    ports:
      - "8501:8501"
    environment: 
      BACKEND_URI: 'http://backend:8000'