vars:
  - config/params.yaml

stages:
  data_preprocessing:
    cmd: .venv/bin/python -m src.data_preprocessing
    deps:
      - ./src/data_preprocessing.py
    outs:
      - data/match_summary.csv
  data_ingestion:
    cmd: .venv/bin/python -m src.data.data_ingestion
    deps:
      - ./src/data/data_ingestion.py
      - ./config/params.yaml
      - ./data/match_summary.csv
    params:
      - config/params.yaml:
          - data_ingestion.test_size
    outs:
      - data/raw

  model_building:
    cmd: .venv/bin/python -m src.train
    deps:
      - ./src/data/data_ingestion.py
      - ./data/match_summary.csv
      - ./src/train.py
    params:
      - config/params.yaml:
          - algorithm
          - linear_regression
          - random_forest
          - xgboost
    outs:
      - models/score_prediction.pkl

  model_evaluation:
    cmd: .venv/bin/python -m src.evaluate
    deps:
      - models/score_prediction.pkl
      - ./src/evaluate.py
      - ./src/train.py
    outs:
      - models/experiments_info.json

  model_registration:
    cmd: .venv/bin/python -m src.register_model
    deps:
      - models/experiments_info.json
      - src/register_model.py


